### PR TITLE
Changes: Made changes on header and footer part

### PR DESCRIPTION
**Pull request by Bhumika1312**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
#147 

## Description
[Please include a brief description of the changes or features added]
Have made some changes in header and footer part to make it similar with the original one

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Bhumika1312** [comment]
@arghadipmanna101 Can you check this I have made changes on the updated clone.

**Comment by arghadipmanna101** [comment]
Not look good.

image

**Comment by Bhumika1312** [comment]
image
Sir I have made footer like this

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once

**Comment by Bhumika1312** [comment]
@arghadipmanna101 can you now check now

**Comment by arghadipmanna101** [comment]
The previous footer is better and original as flipkart.

**Comment by Bhumika1312** [comment]
So sir what changes should I do I have also updated header file

**Pull request closed without merging**
