### PR TITLE
 ADDED Dropdown feature in the FAQ section

### PR DESCRIPTION
**Pull request by ANIRUDH130903**
I have added the dropdown feature in the FAQ section using Accordian and js.

## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description
[Please include a brief description of the changes or features added]-I have add the dropdown feature using (+, -) sign and also used the js for the particular function .Also change the font color of the question the faq section. 

## Type of PR

- [X ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ X] I have performed a self-review of my code
- [ X] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]
Screenshot 2024-06-06 224226

##issue number-709

### CODE REVIEW

**Comment by ANIRUDH130903** [comment]
@arghadipmanna101 
Good evening sir 
I have change the dropdown feature in the FAQ section . Please do approve the issue , if you find this correct.
Thank you .

**Comment by arghadipmanna101** [comment]
Work on the updated page.

**Comment by arghadipmanna101** [comment]
> @arghadipmanna101 please check this out

Plz work on the updated page . 
link : https://flipkart-clone-seven-azure.vercel.app/

First run the git pull command and then re commit all things.

**Comment by ANIRUDH130903** [comment]
@arghadipmanna101 I have updated the dropdown feature in the updated pages .Can you please tell me where do I submit my code .
Screenshot 2024-06-19 230508

**Pull request merged**
