### PR TITLE
Navabar.html

### PR DESCRIPTION
**Pull request by Meetjain1**
updated The dropdown navbar of profile with the actual dropdown navbar of Flipkart

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
there have a conflict. check it and then you make a PR

**Comment by Meetjain1** [comment]
@arghadipmanna101 sorry sir just missed it , now the conflict has been resolved Thankyou.

**Comment by arghadipmanna101** [comment]
> @arghadipmanna101 sorry sir just missed it , now the conflict has been resolved Thankyou.

thanks for your confirmation

**Comment by Meetjain1** [comment]
@arghadipmanna101 please label as gssoc

**Pull request merged**
