### PR TITLE
Favicon issue resolved

### PR DESCRIPTION
**Pull request by samyakmaitre**
## Related Issue
Favicon  |  Kindly accept my PR and assign gssoc label

## Description
Favicon was not visible

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
There was some html syntax error and incorrect file name.

### CODE REVIEW

**Comment by samyakmaitre** [comment]
Task is performed on updated webpage.

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once.

**Comment by samyakmaitre** [comment]
Conflict issue resolved. Kindly add this PR under gssoc label level 2 if possible since I have worked on this twice.
Thank you.

**Comment by arghadipmanna101** [comment]
Issue : 

image

**Pull request closed without merging**
