### PR TITLE
Added the the main content that should be on a shoping website

### PR DESCRIPTION
**Pull request by sshivangi882**
fixed issuse #30

So , the website is looking like this after changes, I have also added hover effects on the products images.

Screenshot (841)

Screenshot (840)

Screenshot (838)
Screenshot (839)

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
image

what is this @sshivangi882 . check it once

**Comment by sshivangi882** [comment]
It was not done by me. and some have removed the jQuery which is attaching all the pages onto the index page.

**Comment by arghadipmanna101** [comment]
> It was not done by me. and some have removed the jQuery which is attaching all the pages onto the index page.

Can you resolve this?

**Comment by sshivangi882** [comment]
yeah ! Sure

**Comment by arghadipmanna101** [comment]
> yeah ! Sure

thank you

**Pull request merged**
