### PR TITLE
Added the feature to auto comment on pull request being raised

### LINKED ISSUE #744: Auto commenting feature for new PR raised
This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs. By automatically commenting on PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

Could you please assign me this issue under GSSOC'24.

### PR DESCRIPTION
**Pull request by suhanipaliwal**
## Related Issue
Fixes #744 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
There have some issues check it once

**Comment by suhanipaliwal** [comment]
> There have some issues check it once

I have checked it and I don't think there are any issues. Can you please specify what issue you faced?

**Comment by arghadipmanna101** [comment]
Do Git pull and then commit all your code and push them. Then recreate new PR.

**Comment by suhanipaliwal** [comment]
> Do Git pull and then commit all your code and push them. Then recreate new PR.

This issue simply involves adding a file in the .github directory to add the necessary workflow. Git pull is not necessary for this issue. Could you please merge this pr and add the labels for gssoc.

**Pull request closed without merging**
