### PR TITLE
Added Grievance redressal page

### PR DESCRIPTION
**Pull request by jency1**
## Related Issue
Completed #1534 

## Description
Added Grievance Redressal Page.

@arghadipmanna101 Please review and merge this PR as soon as possible.

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
hello @jency1 
you have not assign this issue how you can create PR

**Comment by SadafKausar2025** [comment]
hello @jency1 
this issue is also assign to me

**Comment by arghadipmanna101** [comment]
resolve conflicts.

**Comment by jency1** [comment]
> resolve conflicts.

@arghadipmanna101 I have resolved the conflict issues. Please merge this PR.

**Comment by jency1** [comment]
@arghadipmanna101 I have resolved all the conflict issues. Please merge this PR.

**Comment by jency1** [comment]
@arghadipmanna101 I have resolved all the conflict issues. Please merge this PR as soon as possible.

**Comment by jency1** [comment]
@arghadipmanna101 I have resolved all the conflict issues. Please merge this PR as soon as possible.

**Pull request merged**
