### PR TITLE
Aligned content

### PR DESCRIPTION
**Pull request by dishathakurata**
Fixes issue #267 

Oneplus box aligned
updated

### CODE REVIEW

**Comment by dishathakurata** [comment]
@arghadipmanna101 Please review my PR

**Comment by YashkShrivas4491** [comment]
Note: Your branch has a merge conflict so resolve this issue ok and update it with the upstream means updated website

**Comment by YashkShrivas4491** [comment]
Ex : 
WhatsApp Image 2024-05-16 at 09 54 21_b8cd41d0

Just you have to click on update branch or resolve conflict manually ok

**Comment by arghadipmanna101** [comment]
> Ex : WhatsApp Image 2024-05-16 at 09 54 21_b8cd41d0
> 
> Just you have to click on update branch or resolve conflict manually ok

right. @dishathakurata plz follow what @YashkShrivas4491 say. ok

**Comment by dishathakurata** [comment]
@arghadipmanna101 updated
Conflict resolved
Now please review my PR

**Pull request merged**
