### PR TITLE
Added hover effects to social icons & footer elements

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
Solved issue #472

This pull request adds hover effects to social media icons and footer elements, enhancing user interaction and visual appeal. The hover effects improve the overall user experience by providing visual feedback when interacting with these elements.

https://github.com/arghadipmanna101/Flipkart_Clone/assets/109781385/fc0608f9-e3f0-4955-8344-ba4a27fb3040

### CODE REVIEW

**Comment by YashkShrivas4491** [comment]
@arghadipmanna101 LGTM

**Comment by arghadipmanna101** [comment]
Do the same thing in the updated website.

**Comment by thevijayshankersharma** [comment]
@arghadipmanna101 Done

**Comment by YashkShrivas4491** [comment]
> @arghadipmanna101 Done

Great ✅ @thevijayshankersharma

**Comment by thevijayshankersharma** [comment]
@arghadipmanna101 you didn't assign any level label under gssoc.

**Pull request merged**
