### PR TITLE
Fixed #231 Arrow of carousel redeveloped and aligned properly

### LINKED ISSUE #231: BUG: Arrow of slidebar is misplaced and different from flipkart's website.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The arrow of slidebar is not like flipkart's slidebar arrow. It needs to be fixed for positioning and size.
Screenshot 2024-05-11 212754
Screenshot 2024-05-11 212746

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by shnwz-solves**
Hi PA,
#Fixed issue no. #231 Arrow of carousel redeveloped and aligned properly and carousel indicators also developed and aligned as original flipkart's website.
I have fixed the issue by making changes in index.html file. I changed the carousel arrow's and carousel indicator's design and position according to original flipkart's website. Also replaced 3 banner images of the carousel to make it more like original flipkart's website.

### Screenshot
Previous:
issue #231 carousel

### Now:
#Fixed #231 Arrow of carousel redeveloped and aligned properly

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
Do the same woke in the updated website. ok

**Comment by shnwz-solves** [comment]
> Do the same woke in the updated website. ok
Hello PA, @arghadipmanna101 
I have solved the issue in original webiste which I found on the code section of the project which is: 
https://flipkart-clone-seven-azure.vercel.app/

If there is any other website which you're talking about then please do share the link here.
ThankYOu.

**Comment by arghadipmanna101** [comment]
> > Do the same woke in the updated website. ok
> 
> Hello PA, @arghadipmanna101 I have solved the issue in original webiste which I found on the code section of the project which is: https://flipkart-clone-seven-azure.vercel.app/
> 
> If there is any other website which you're talking about then please do share the link here. ThankYOu.

https://flipkart-clone-seven-azure.vercel.app/
This the website link . work on the updated website.ok.

**Comment by shnwz-solves** [comment]
> > > Do the same woke in the updated website. ok
> > 
> > 
> > Hello PA, @arghadipmanna101 I have solved the issue in original webiste which I found on the code section of the project which is: https://flipkart-clone-seven-azure.vercel.app/
> > If there is any other website which you're talking about then please do share the link here. ThankYOu.
> 
> https://flipkart-clone-seven-azure.vercel.app/ This the website link . work on the updated website.ok.

Hey PA, the link you have provided and what I am getting after cloning the repo are very different. 
Am I doing any mistake, please rectify it. I have attached the video .

https://github.com/arghadipmanna101/Flipkart_Clone/assets/126380641/912c08b7-400b-436a-b1a9-48e784c1e26d

**Pull request closed without merging**
