### PR TITLE
index.html

### PR DESCRIPTION
**Pull request by Meetjain1**
Added bottom most footer , added (copyright , payment options and many more)

all images added are attached 

mastercard

visa

emi

cash on delivery

net banking

discover

rupay

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
There have some conflict check it once and then create a new PR

**Comment by Meetjain1** [comment]
@arghadipmanna101 check it once now sir

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once. and then recreate a new PR

**Comment by Meetjain1** [comment]
@arghadipmanna101 don't know why it's is showing (there is no conflict) in my UI , no issue will create a new PR sir

**Comment by Meetjain1** [comment]
@arghadipmanna101 sir ,created a new pr #250 , hence closing this Thankyou

**Pull request closed without merging**
