### PR TITLE
Terms of uses added

### PR DESCRIPTION
**Pull request by Ansh101112**
## Related Issue
#1441 

## Description
Screenshot (260)

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Ansh101112** [comment]
@arghadipmanna101 sir conflicts resolved

**Comment by arghadipmanna101** [comment]
conflict issue

**Comment by Ansh101112** [comment]
> conflict issue

Okay sir fixing it rn

**Comment by Ansh101112** [comment]
@arghadipmanna101 sir conflicts fixed please see now.

**Pull request merged**
