### PR TITLE
Created Orders Page 

### PR DESCRIPTION
**Pull request by anandachanta19**
I have contributed toward the project by replicating Filpkart orders page !
here are the screen shots of order page

Screenshot (52)

Screenshot (53)

### CODE REVIEW

**Comment by anandachanta19** [comment]
@arghadipmanna101  Actually I was assigned for the orders page but some other has created an orders page that does'nt replicates flipkarts order page. Due to that I have conflicts with the main branch.Please check and accept my pull request. I actually replicated the Flipkart order page.

**Comment by anandachanta19** [comment]
> There have a conflict issue check it once.

yeah I have checked. The problem is some other guy have already added an order.html in the main branch of your repository. Actually I was assigned for the orders page. That's the reason I am getting the conflict  issues.

This the one added in the original repository.

Screenshot (54)

and that order.html looks like this
Screenshot (55)
That does'nt even replicate flipkart's order page.

so please remove that order.html then my conflicting issues will be resolved. @arghadipmanna101 Please do check!

**Comment by arghadipmanna101** [comment]
There have a conflict issue check it once and then recreate a new PR. ok

**Comment by anandachanta19** [comment]
conflict issues resolved @arghadipmanna101

**Pull request closed without merging**
