### PR TITLE
Made changes in FAQ

### PR DESCRIPTION
**Pull request by kesharwaniyanshi**
## Description
I added icons in Faq an also made it collapsible on clicking anywhere in the box and not just the text . 

## Type of PR

- [X] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image
image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once and then make a new PR. ok

**Comment by kesharwaniyanshi** [comment]
> There have some conflict issue check it once and then make a new PR. ok

Conflicts have been resolved. Still i need to make new PR?

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once and make a new PR. ok

**Comment by kesharwaniyanshi** [comment]
Resolved.

**Pull request merged**
