### PR TITLE
fix signup and signin page

### PR DESCRIPTION
**Pull request by Gokilp**
Assign issue
#27  fix Sign up page and Signin page 

Improvement
- [x]  fixed signup html page 
- [x] fixed signin html page
 - [x]  fixed signup css page 
- [x] fixed signin css page
 
Achievement 

Responsive Ui Improment 

Screenshots 

login page
image

sigin page 

image

### CODE REVIEW

**Comment by Gokilp** [comment]
Fix the issiue sign up page please review my PR @arghadipmanna101

**Comment by Gokilp** [comment]
please review pr @arghadipmanna101

**Comment by arghadipmanna101** [comment]
> please review pr @arghadipmanna101

There have some conflict issue. check it once. then create a new PR. ok

**Comment by Gokilp** [comment]
make new pr of issue  facing the merge conflicts error

**Pull request closed without merging**
