### PR TITLE
Added link to download app section under 3 dots of our navbar right side

### PR DESCRIPTION
**Pull request by PrabhjotBajwa**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [x] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
@arghadipmanna101 plz merge my changes to main branch under gssoc24 label #578

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once and make a new PR. ok

**Comment by arghadipmanna101** [comment]
image

There have some issue check it once.

**Comment by arghadipmanna101** [comment]
issue:

image

**Comment by PrabhjotBajwa** [comment]
from my side all is set plz merge this issue under gsssoc24 label

**Pull request merged**
