### PR TITLE
Fix: Made cards responsive.

### PR DESCRIPTION
**Pull request by nagalakshmi08**
## Related Issue
Fixes issues #633 & #719 

## Description
Changed and added styles to cards section to make them responsive , now the cards are not overflowing.

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Please check it and let me know if any changes. Thank you.

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
There have some issues check it once

**Comment by nagalakshmi08** [comment]
> There have some issues check it once

Hi, can I know what the issues are?

**Comment by arghadipmanna101** [comment]
There have some issue check it once .

**Comment by arghadipmanna101** [comment]
There have some issue. check it once

**Pull request closed without merging**
