### PR TITLE
Social Media Handles Updated #425

### PR DESCRIPTION
**Pull request by Ayush170803**
Successfully updated the social media handles of respective icons on footer

### CODE REVIEW

**Comment by Ayush170803** [comment]
@arghadipmanna101 please check the updated code and merge it

**Comment by arghadipmanna101** [comment]
Do same things in the updated website ok

**Comment by Ayush170803** [comment]
updated the code in updated website kindly merge it

**Comment by Ayush170803** [comment]
@arghadipmanna101  please add gssoc and level2 in pull request also

**Comment by Ayush170803** [comment]
In issue I have labelled as level 2 but in pull request it's labelled is level1 kindly update it

**Comment by Ayush170803** [comment]
@arghadipmanna101 In issue I have been labelled as level 2 but in pull request it's labelled is level1 kindly update it

**Comment by Ayush170803** [comment]
@arghadipmanna101 in issue I have been labelled as level 2 but in pull request it's labelled is level1 kindly update it

**Pull request merged**
