### PR TITLE
Changed the nav-items styling and animations

### PR DESCRIPTION
**Pull request by ayush-848**
## Related Issue
#274 

## Description
I have changed the navbar styling to make it look much better. I have made the text highlighted on hover and do the shadowing effect in a more better way.

## Type of PR
* [ ]  Bug fix
* [x]  Feature enhancement
* [ ]  Documentation update
* [ ]  Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
 * [x]  I have performed a self-review of my code
 * [x]  I have read and followed the Contribution Guidelines.
 * [x]  I have tested the changes thoroughly before submitting this pull request.
 * [x]  I have provided relevant issue numbers, screenshots, and videos after making the changes.
 * [ ]  I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by ayush-848** [comment]
@arghadipmanna101 please check my contribution.

**Comment by ayush-848** [comment]
@arghadipmanna101 If you approve of everything then please merge it.
This PR is for issue #274

**Comment by arghadipmanna101** [comment]
NO update is there.

**Comment by ayush-848** [comment]
> NO update is there.

In PR or in website?

**Comment by ayush-848** [comment]
@arghadipmanna101 

image
this is the index.html


image
this is the vercel

why both doesnot match???

**Pull request closed without merging**
