### PR TITLE
Creating The Exact Replica Of Flipkarts Footers

### PR DESCRIPTION
**Pull request by rabinarayanpadhy07**
Creating the Exact Replica of Flipkart's Footer Making It Fully Responsive for All Devices, and Using a Single SVG File for Payment Cards.
**FOR DESKTOP DEVICES**
Screenshot (171)
**FOR TABLETS AND LANDSCAPE DEVICE**
Screenshot (172)
**FOR SMALL SCREEN DEVICE**
Screenshot (173)

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once. and then recreate a new issue.ok

**Comment by rabinarayanpadhy07** [comment]
> There have some conflict issue check it once. and then recreate a new issue.ok


"Hey, I removed all the conflicts. Please merge this."

**Comment by rabinarayanpadhy07** [comment]
which images ???

**Comment by arghadipmanna101** [comment]
image
What is this man. plz check it once

**Comment by rabinarayanpadhy07** [comment]
> image
> What is this man. plz check it once
> 

 "Hey, you are not assigned to this work. You can only assign me to the footer section."

**Pull request closed without merging**
