### PR TITLE
Update Navabar.html

### PR DESCRIPTION
**Pull request by MelissaSequeira**
Updated flipkart navbar

## Related Issue
["None”]

## Description
[In the navbar ,the navliinks were not working properly on hovering.
The searchbar symbol and the input box was not aligned properly anchor tags were not working properly]

## Type of PR

- [done ] Bug fix
- [done ] Feature enhancement
- [ done] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[
fk
]

## Checklist:
- [Yes ] I have performed a self-review of my code
- [Yes ] I have read and followed the Contribution Guidelines.
- [Yes ] I have tested the changes thoroughly before submitting this pull request.
- [Yes ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by MelissaSequeira** [comment]
Sir i have updated the navbar..plz check

**Comment by MelissaSequeira** [comment]
> Work on the updated website. Link : - https://flipkart-clone-seven-azure.vercel.app/

Yes sir but I won't get points for above?

**Comment by arghadipmanna101** [comment]
> And I m not getting access to vercel app

why?

**Comment by MelissaSequeira** [comment]
> > And I m not getting access to vercel app
> 
> why?

its asking for access ,which i didnt get yet

**Pull request closed without merging**
