### PR TITLE
To make products/mobile deals section display as CARDS #454

### PR DESCRIPTION
**Pull request by divyalaldinani**
Title of Issue: To make products/mobile deals section display as CARDS #454
Issue Number: 454

Changes made:
Updated low quality images with high quality images of mobile phones and made the section look good by adding appropriate border, space, fonts etc.

result:
BEFORE:
image

AFTER:
image

### CODE REVIEW

**Comment by divyalaldinani** [comment]
@arghadipmanna101

**Comment by arghadipmanna101** [comment]
There have a conflict issue plz check it once and then recreate a new PR .ok

**Comment by divyalaldinani** [comment]
I think I'll have to delete the fork, so the issue will be closed if I do so.. should I create a new issue then?

**Comment by divyalaldinani** [comment]
resoolved @arghadipmanna101

**Comment by divyalaldinani** [comment]
@arghadipmanna101 hey can you let me know if there's still any problem here?

**Pull request closed without merging**
