### PR TITLE
Update topdeals.js 

### PR DESCRIPTION
**Pull request by kuritika098**
I have added brand name , rating and prices in the respective sections of Top deals,, it makes it more attractive.
Screenshot 2024-05-13 200127

### CODE REVIEW

**Comment by kuritika098** [comment]
I have added Brand names , prices , ratings and discounts on the product section of Top deals.

**Comment by arghadipmanna101** [comment]
Plz work on the updated website.

**Comment by kuritika098** [comment]
What do you mean sir ? did i something wrong?

**Comment by kuritika098** [comment]
@arghadipmanna101 please merge this pull request sir

**Comment by arghadipmanna101** [comment]
@kuritika098 Do same things in the updated website. ok

**Pull request closed without merging**
