### PR TITLE
Category section UI modified 

### LINKED ISSUE #1223: Feat: Change category images with oroginal FP Page images
### Describe the feature

the present images are not exact copies of original one change those

### Describe the solution you'd like

Also add top offers

### Describe alternatives you've considered

add images

### Add ScreenShots

will add once done

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by sau-mili**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

resolves #1223 

## Description
[Please include a brief description of the changes or features added]
- Bug fixed: Spacing between components, and font issue
- Change the category icon images
- Added missing categories
- Fixed font size, alignment, weight
- Improved the category with grid css
- Made the category almost similar to that of original website

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

### BEFORE
Screenshot 2024-06-15 192700

### AFTER
Screenshot 2024-06-15 192653

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by sau-mili** [comment]
@arghadipmanna101 can you check now?

**Comment by arghadipmanna101** [comment]
Issue : 

image

**Comment by sau-mili** [comment]
can you check now?
Screenshot 2024-06-18 235815

**Comment by sau-mili** [comment]
@arghadipmanna101  please check

**Comment by sau-mili** [comment]
@arghadipmanna101 i have resolved conflicts please check

**Comment by sau-mili** [comment]
@arghadipmanna101 check my PR please. And please check it before changing the categorydata.json file. It was originally wrongly aligned, I fixed it twice, but subsequent merges is causing unresolvable conflicts and repitition

**Comment by arghadipmanna101** [comment]
error : 
image

**Comment by sau-mili** [comment]
This can’t be due to my PR only. i haven’t changed any other part of the code. Can you check the previous merges please?

**Comment by arghadipmanna101** [comment]
> This can’t be due to my PR only. i haven’t changed any other part of the code. Can you check the previous merges please?

Ok once do git pull and then recreate a new pr .

**Comment by sau-mili** [comment]
If I pull the changes, then these bugs will add up to my edits too.. Can you please tell me once this is figured out? Since, the json file editing required a lot of changes, and took me really long time to fix thrice before since, PRs that were done after My PR was merged before this.

**Comment by arghadipmanna101** [comment]
> If I pull the changes, then these bugs will add up to my edits too.. Can you please tell me once this is figured out? Since, the json file editing required a lot of changes, and took me really long time to fix thrice before since, PRs that were done after My PR was merged before this.

https://flipkart-clone-seven-azure.vercel.app/
This is my present website, you can check there have no error.

**Comment by sau-mili** [comment]
i am doing a new pull

**Pull request closed without merging**
