### PR TITLE
EPR Compliance Page Added

### PR DESCRIPTION
**Pull request by jency1**
## Related Issue
Completed #1535

@arghadipmanna101 Please review and merge this PR as soon as possible.

## Description
EPR Compliance Page Added

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [x] Other (specify): _______________

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
resolve conflicts.

**Comment by jency1** [comment]
> resolve conflicts.

@arghadipmanna101 I have resolved all the conflict issues. Please merge this PR as soon as possible.

**Comment by jency1** [comment]
@arghadipmanna101 I have resolved all the conflict issues. Please merge this PR as soon as possible.

**Comment by jency1** [comment]
@arghadipmanna101 I have resolved all the conflict issues. Please merge this PR as soon as possible.

**Comment by arghadipmanna101** [comment]
resolve conflicts.

**Pull request merged**
