### PR TITLE
Solved Bug: The cloned website is malfunctioning and differs significantly from the original.

### PR DESCRIPTION
**Pull request by Bhumika1312**
…site

## Related Issue
#147

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

Before:

Screenshot 2024-05-11 073100

After:

image

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Bhumika1312** [comment]
@arghadipmanna101 Can you please add gssoc label and level on this PR an assign it to me

**Comment by arghadipmanna101** [comment]
image

are you this? @Bhumika1312

**Comment by Bhumika1312** [comment]
@arghadipmanna101  Yes I solve this error

**Comment by arghadipmanna101** [comment]
image

Steel there have

**Comment by Bhumika1312** [comment]
Sir I made a new file name changes and in that I have made all the changes can you check once if it correct or I have to again solve it

**Comment by arghadipmanna101** [comment]
Work in the updated page : https://flipkart-clone-seven-azure.vercel.app/

**Comment by Bhumika1312** [comment]
I have made some changes to the header and footer and opened a new pull request.

**Pull request closed without merging**
