### PR TITLE
Feat: Add Quantity Button

### PR DESCRIPTION
**Pull request by SrinivasDevolper**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

When a user wants more than one product, we need to add a quantity button that gives users a convenient real-time experience.

## Description
[Please include a brief description of the changes or features added]

I added the Quantity Button Feature

Issue no: #1050

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

https://github.com/arghadipmanna101/Flipkart_Clone/assets/121508628/1772cee8-6d3d-4514-bfd5-7b68c139d922

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

**If it's not good, please assign me again I will do it better**

**I expect a level 3 label**

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once.

**Comment by SrinivasDevolper** [comment]
> There have some conflict issue check it once.

Please add Level Labels on this PR

**Comment by arghadipmanna101** [comment]
What is this man? 

image

**Comment by SrinivasDevolper** [comment]
> What is this man?
> 
> image

What happend, I didn't understand

**Pull request closed without merging**
