### PR TITLE
updated chatbot #812

### PR DESCRIPTION
**Pull request by DevNandini02**
## Related Issue
#812 

## Description
Earlier the chatbot wasn't responding to the queries. But now i have added a knowledge base as well as integrated AI for responding to the user's queries.

## Type of PR

- [X] Bug fix

## Screenshots / videos (if applicable)

https://github.com/arghadipmanna101/Flipkart_Clone/assets/124669890/a98eec1e-9c1e-42f8-8e31-2154aaab2bc7

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by DevNandini02** [comment]
@arghadipmanna101 please add the gssoc label and level for this task.

**Comment by arghadipmanna101** [comment]
Make it better. This is not good

**Comment by DevNandini02** [comment]
> Make it better. This is not good

Is it for the styling or the working of the chatbot?

**Comment by arghadipmanna101** [comment]
Both

**Comment by DevNandini02** [comment]
> Both

Okay i'll look into it and update soon.

**Comment by Garima-149** [comment]
@DevNandini02  Could you please tell that where did you find this chatbot option? in code file

**Pull request closed without merging**
