### PR TITLE
Updated Flipkart plus 

### LINKED ISSUE #533: Improving Flipkart plus zone page
The text in the image is not clearly visible.
Fixing navbar adding search icon and dark mode.
Adding some products .
Fotter also need some improvements.
Screenshot_20240516-074123

### PR DESCRIPTION
**Pull request by gaddevinay**
# Fixes Issue🛠

Closes #533

# Description👨‍💻 

-Added search icon in Flipkart plus zone page.
-Updated banner
-Make footer more responsive

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

I have checked locally on my pc

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an GSSOC Open Source Contributor

# Screenshots/GIF📷

https://github.com/arghadipmanna101/Flipkart_Clone/assets/128584849/6d33dbcb-61da-4638-888e-6c2154d085f3

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once

**Comment by gaddevinay** [comment]
Solved conflicts

**Comment by arghadipmanna101** [comment]
image

what is this man. check it once

**Comment by gaddevinay** [comment]
solved that is because of missing ' } '

**Pull request merged**
