### PR TITLE
Updated Ads and Main page

### PR DESCRIPTION
**Pull request by SahithiDevalla**
I have edited good pictures for ads, and created  good main page sections

### CODE REVIEW

**Comment by SahithiDevalla** [comment]
please check this

**Comment by arghadipmanna101** [comment]
> please check this

great work. thanks for contributing @SahithiDevalla

**Comment by SahithiDevalla** [comment]
Thank you for merging! :)
Can i delete branch now, I am new here , can u guide pls.

**Comment by arghadipmanna101** [comment]
> Thank you for merging! :) Can i delete branch now, I am new here , can u guide pls.

Why you want to delete the branch?

**Comment by SahithiDevalla** [comment]
It is showing there to delete it.
can u tell will my contribution count for leaderboard, please consider it, this is my first contribution, they said it starts from 7 pm onwards, can u do anything about it.
can i make a pr again after 7 with same changes and can u merge it please.

**Comment by arghadipmanna101** [comment]
I don't know about it. you can contract with GSSOC'24 management team. ok

**Comment by SahithiDevalla** [comment]
They posted the kickoff will be after 7 so many ppl stopped crating pr's , i will loose points in it, can u help me in this please
is there any change to revert pr and i can make it again

**Pull request merged**
