### PR TITLE
Update footer of index.css

### PR DESCRIPTION
**Pull request by vaishali-sharma-20**
## Related Issue
Issue no.- #825 and #985 

## Description
Correction in Footer.

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
**Before: **
Screenshot 2024-06-02 225154

**FIxed:**
Screenshot 2024-06-03 083514

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once and then make a new PR ok.

**Comment by arghadipmanna101** [comment]
Work on the updated website. Link : - https://flipkart-clone-seven-azure.vercel.app/

**Comment by vaishali-sharma-20** [comment]
@arghadipmanna101 for vercel , It's asking for team access.

**Comment by arghadipmanna101** [comment]
> @arghadipmanna101 for vercel , It's asking for team access.

Means?

**Pull request closed without merging**
