### PR TITLE
Improved The NavBar -Same as The actual website

### PR DESCRIPTION
**Pull request by aditi75432**
## Related Issue
improved the navbar. its same as the actual website and much better

## Description
more aligned

## Type of PR

- [X ] Bug fix
- [ X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________
- Closes https://github.com/arghadipmanna101/Flipkart_Clone/issues/779

## Screenshots / videos (if applicable)

Screenshot 2024-05-31 162217

https://github.com/arghadipmanna101/Flipkart_Clone/assets/141945188/88ce658b-7e0c-4a6c-8ef0-3a69a4302f4d

## Checklist:
- [X ] I have performed a self-review of my code
- [ X] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by aditi75432** [comment]
@arghadipmanna101 sir please add gssoc and level 1 label to it accept my pull request
it is better than before

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once and then make a new PR. ok

**Comment by aditi75432** [comment]
Ok sir

**Comment by aditi75432** [comment]
@arghadipmanna101 the conflicts have been resolved . kindly check

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once and make a new PR. ok

**Comment by aditi75432** [comment]
@arghadipmanna101 sir the conflicts have been resolved . kindly check
also it seems that someone has been making changes to the main branch . kindly see to that too

**Comment by aditi75432** [comment]
@arghadipmanna101 sir kindly accept my pull request . it will be my very first. also add gssoc and level 1 label to it

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once and make a new PR. ok

**Pull request closed without merging**
