### PR TITLE
✨ Feat: Design a Terms of Use Page for Flipcart clone 

### LINKED ISSUE #1529: ✨ Feat: Design a Terms of Use Page for Flipcart clone
### Describe the feature

Hey @arghadipmanna101 

I would like to design and add a terms of use page for this website matched to the design of Flipcart

image

Could you please assign this issue to me?

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by MastanSayyad**
Hey @arghadipmanna101 

- fixes  #1529

I have designed and created a Terms of Use Page for Flipcart clone 

image

image

image

Please take a look and merge this PR

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@arghadipmanna101 Pls merge this PR before 7PM so that it get count under gssoc!

**Comment by MastanSayyad** [comment]
@arghadipmanna101 pls merge this PR

**Comment by arghadipmanna101** [comment]
Done ✅ bro! Before 7pm ✌️

**Comment by MastanSayyad** [comment]
> Done ✅ bro! Before 7pm ✌️

That was close, Thank you so much bro!

**Pull request merged**
