### PR TITLE
Changed the look of Top deals section

### PR DESCRIPTION
**Pull request by SadafKausar2025**
## Related Issue #715
Feat: Changing the look of Top deal section

## Description
I have made card and added images and also button to add to card with icons
and also I have written the imformation related to that content
now the top deal section look very good

## Type of PR

- [x] Feature enhancement

## Screenshots / videos (if applicable)

https://github.com/arghadipmanna101/Flipkart_Clone/assets/137484958/678fe2ef-8e59-4b0d-9795-6d5deed96465

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
Hey @arghadipmanna101 
I have resolved all conflicts please merge it
You have already assigned me issue but not yet merged

**Review by SyedImtiyaz-1 — APPROVED** [review]
@arghadipmanna101 ,
Kindly merge the PR 👍🏻

**Comment by arghadipmanna101** [comment]
> Hey @arghadipmanna101 I have resolved all conflicts please merge it You have already assigned me issue but not yet merged

Steel there have some conflict issue

**Comment by SadafKausar2025** [comment]
> > Hey @arghadipmanna101 I have resolved all conflicts please merge it You have already assigned me issue but not yet merged
> 
> Steel there have some conflict issue

ok I am resolving

**Comment by SadafKausar2025** [comment]
hello @arghadipmanna101 
is it now correct?
conflicts are resolved

**Comment by SadafKausar2025** [comment]
Thank You @arghadipmanna101  for merging my PR

**Pull request merged**
