### PR TITLE
Changes made in category list dropdown

### PR DESCRIPTION
**Pull request by MaragathaMeenakshi**
Closing Issue number : #698 

## Description
I have enhanced the UI of the navigation bar by incorporating multiple dropdowns, similar to the design on the Flipkart website.
- Added hovering functionality to the dropdown elements: When an element is clicked, a sub-dropdown menu is displayed.
- Resolved the blinking issue when hovering over the dropdown.
- Adjusted the position of elements to align with the Flipkart website design.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/arghadipmanna101/Flipkart_Clone/assets/113226919/2a1ae02d-06cd-4e93-8076-9eeede14ad5b

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by MaragathaMeenakshi** [comment]
Okey

**Comment by MaragathaMeenakshi** [comment]
I could not view the deployment. 
Could you help me?
@arghadipmanna101 . Could You add me to the discord server of this project.

**Comment by arghadipmanna101** [comment]
> I could not view the deployment. Could you help me? @arghadipmanna101 . Could You add me to the discord server of this project.

Can you DM me in LinkedIn?

**Comment by MaragathaMeenakshi** [comment]
Hi @arghadipmanna101  
Could you add labels and assign me this . 
then explain me about the issue because I could not view the deployment.

**Comment by arghadipmanna101** [comment]
Work on the updated website. Link : - https://flipkart-clone-seven-azure.vercel.app/

**Comment by MaragathaMeenakshi** [comment]
Kindly view the changes @arghadipmanna101 made in new ui.

**Pull request merged**
