### PR TITLE
Added items to the toys list ,stationary and dessert items.

### PR DESCRIPTION
**Pull request by pani2004**
Solved Issue #383 
Screenshot (33)
Screenshot (34)

### CODE REVIEW

**Comment by pani2004** [comment]
Solved the issue #383. Added different items in the lists. Please check the PR.

Screenshot (31)
Screenshot (32)

**Comment by pani2004** [comment]
@arghadipmanna101 Please review the PR

**Comment by pani2004** [comment]
@arghadipmanna101 Please review the PR.

**Comment by pani2004** [comment]
@arghadipmanna101 can u please look into it?

**Comment by arghadipmanna101** [comment]
image

some errors are there check it once

**Comment by pani2004** [comment]
@arghadipmanna101 I think u have already merged someone else's PR for the same issue.

**Comment by pani2004** [comment]
@arghadipmanna101 Pls specify the errors!!!

**Comment by arghadipmanna101** [comment]
> @arghadipmanna101 Pls specify the errors!!!

image

**Pull request closed without merging**
