### PR TITLE
Again Update topdeals.js

### PR DESCRIPTION
**Pull request by kuritika098**
Screenshot 2024-05-13 200127

I have added prices , ratings , discounts and brands on the flipkart clone to make it more attractive and user friendly.

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
plz do the same things in the updated website. ok

**Comment by kuritika098** [comment]
sir , that's what i am not able to understand what is this mean?
From where ?

**Comment by kuritika098** [comment]
It would be great sir @arghadipmanna101 , if you tell from where i have to make changes. please sir , thank you

**Comment by arghadipmanna101** [comment]
DM me in LinkedIn .ok @kuritika098

**Comment by kuritika098** [comment]
ok sir

**Pull request closed without merging**
