### PR TITLE
Add a preloader

### PR DESCRIPTION
**Pull request by DharshiBalasubramaniyam**
The loader looks like below.
Screenshot 2024-05-10 183448

### CODE REVIEW

**Comment by DharshiBalasubramaniyam** [comment]
@arghadipmanna101 This pr fixes #92. Please review this pr.

**Comment by arghadipmanna101** [comment]
> @arghadipmanna101 This pr fixes #92. Please review this pr.

give me a video of your work.

**Comment by DharshiBalasubramaniyam** [comment]
> > @arghadipmanna101 This pr fixes #92. Please review this pr.
> 
> give me a video of your work.

Uploading preloader 2.mp4…

**Comment by arghadipmanna101** [comment]
This is not working. Check it once

> > > @arghadipmanna101 This pr fixes #92. Please review this pr.
> > 
> > 
> > give me a video of your work.
> 
>  preloader.2.mp4

**Comment by DharshiBalasubramaniyam** [comment]
> This is not working. Check it once
> 
> > > > @arghadipmanna101 This pr fixes #92. Please review this pr.
> > > 
> > > 
> > > give me a video of your work.
> > 
> > 
> > preloader.2.mp4

I have not pushed the updated code (adding the preloader in the index.html) in the pull request.

For demo purpose I have just add it in index.html and took a video. So have to add the preloader in the index.html.

**Comment by arghadipmanna101** [comment]
> > This is not working. Check it once
> > > > > @arghadipmanna101 This pr fixes #92. Please review this pr.
> > > > 
> > > > 
> > > > give me a video of your work.
> > > 
> > > 
> > > preloader.2.mp4
> 
> I have not pushed the updated code (adding the preloader in the index.html) in the pull request.
> 
> For demo purpose I have just add it in index.html locally and took a video. So have to add the preloader in the index.html.

ok

**Pull request merged**
