### PR TITLE
Links are working now with minor changes in code.

### PR DESCRIPTION
**Pull request by PrabhjotBajwa**
## Related Issue
Links are working now with minor changes in code.

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [x] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
@arghadipmanna101 solved issue no #1038 plz merge my pr under gssoc24 label.

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
Work in the present website.

**Comment by PrabhjotBajwa** [comment]
i am working but still giving error

**Comment by PrabhjotBajwa** [comment]
i sync ur website and then use command git pull to ensure updates but giving error while mergeing pr

**Comment by PrabhjotBajwa** [comment]
links working

**Pull request merged**
