### PR TITLE
Fixed Footer

### PR DESCRIPTION
**Pull request by jency1**
## Related Issue
#780 Fixed

## Description
Fixed the footer. Now it looks similar to the original footer on the flipkart.com website.

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jency1** [comment]
@arghadipmanna101 Please review and merge this PR. 

Add the labels also.

**Comment by jency1** [comment]
@arghadipmanna101 Please review and merge this PR.

Add the labels also.

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once and then make a new PR. ok

**Comment by jency1** [comment]
> There have some conflict issue check it once and then make a new PR. ok

@arghadipmanna101 Please review and merge this PR.

I have solved the conflict issues. 

Add the labels also.

**Comment by jency1** [comment]
@arghadipmanna101 Please review and merge this PR.

I have solved the conflict issues.

**Comment by jency1** [comment]
@arghadipmanna101  Thanks for merging the PR. 

Can you change the level from level2 to level3 as I have changed almost the whole code in html for fixing this issue. Also half of the css code. 

If it's possible then please change this level to level3. 

Thank you.

**Pull request merged**
