### PR TITLE
Directory Structure improved

### PR DESCRIPTION
**Pull request by kashnx**
## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once and make a new PR. ok

**Comment by kashnx** [comment]
No conflicts.Please merge it first, as I have edited it atleast 4-5 times.

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once and then make a new PR ok.

**Comment by arghadipmanna101** [comment]
image

image

image

Those many errors are there. check it

**Comment by arghadipmanna101** [comment]
image

This problem is still there.

**Pull request closed without merging**
