### PR TITLE
fixed footer

### LINKED ISSUE #565: Text not displaying_BUG:
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Text is not displaying currently currently in our website @arghadipmanna101 sir assign this issue to me I will fix this bug . Thankyou

i12

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Meetjain1**
## Related Issue
closes #565 

## Description
Fixed 
1) Text display 
2) Hover effect of social links and footer ends 
3) Responsiveness of footer 
4) Added correct background to the footer

## Type of PR

- [X] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
Work in the present website.

**Comment by Meetjain1** [comment]
> Work in the present website.

This changes are done in present website @arghadipmanna101

**Comment by arghadipmanna101** [comment]
> > Work in the present website.
> 
> This changes are fixed in present website @arghadipmanna101

Same issue.

**Comment by Meetjain1** [comment]
> > > Work in the present website.
> > 
> > 
> > This changes are fixed in present website @arghadipmanna101
> 
> Same issue.

Arae I mean I fixed these changes in present website itself. Not in old website 
You can check the code changes if and the code that is already present. 
Request to please check it once @arghadipmanna101

**Comment by Meetjain1** [comment]
@arghadipmanna101 have a look on this pr. Thanks

**Comment by arghadipmanna101** [comment]
Issue :
image
The footer part comes 2 times.

**Comment by Meetjain1** [comment]
> Issue : image The footer part comes 2 times.

extremely sorry for this , I have fixed it can you check it now @arghadipmanna101

**Comment by Meetjain1** [comment]
@arghadipmanna101 have a look on this pr

**Comment by arghadipmanna101** [comment]
Conflict issues

**Comment by Meetjain1** [comment]
> Conflict issues

@arghadipmanna101 resolved

**Comment by arghadipmanna101** [comment]
not resolved

**Comment by Meetjain1** [comment]
> not resolved

@arghadipmanna101 can you check it once again ?

**Comment by Meetjain1** [comment]
@arghadipmanna101 no conflict issues ,can you please check and merge bz conflict issues will generate whenever there is a new commit merged in these three files.

**Comment by arghadipmanna101** [comment]
image

**Comment by Meetjain1** [comment]
> image

please wait for a while I am resolving it in a minute .

**Comment by arghadipmanna101** [comment]
> > image
> 
> please wait for a while I am resolving it in a minute . @arghadipmanna101

ok

**Comment by Meetjain1** [comment]
@arghadipmanna101 done , please check

**Comment by Meetjain1** [comment]
Screenshot 2024-07-15 235642

**Comment by arghadipmanna101** [comment]
image

What is this man? add some CSS to look better ok

**Comment by Meetjain1** [comment]
> image
> 
> What is this man? add some CSS to look better ok

@arghadipmanna101 This is not done by me . This was done by others See my commit I only changed css of footer not added these text.

**Comment by Meetjain1** [comment]
> > > image
> > > What is this man? add some CSS to look better ok
> > 
> > 
> > @arghadipmanna101 This is not done by me . This was done by others See my commit I only changed css of footer not added these text.
> 
> ok

Thanks for understanding @arghadipmanna101 .

**Pull request merged**
