### PR TITLE
added contact us page

### PR DESCRIPTION
**Pull request by ayush-848**
## Related Issue
#872 

## Description
Added a responsive contact_us page

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by ayush-848** [comment]
@arghadipmanna101 please check, I have put a lot of effort in it

**Comment by ayush-848** [comment]
@arghadipmanna101  please check the PR, I have put a lot of effort in it

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once.

**Comment by arghadipmanna101** [comment]
Website is not working properly.  Only pre loader is working.

image

**Comment by ayush-848** [comment]
@arghadipmanna101 now check.

**Comment by ayush-848** [comment]
@arghadipmanna101 I checked in my laptop. The site opens.

**Comment by ayush-848** [comment]
@arghadipmanna101 Now it should be fine. Please check

**Comment by arghadipmanna101** [comment]
> @arghadipmanna101 Now it should be fine. Please check

Still same problem.

**Comment by ayush-848** [comment]
@arghadipmanna101 Please merge it fast before other conflicts occurs

**Comment by ayush-848** [comment]
@arghadipmanna101 check

**Comment by ayush-848** [comment]
@arghadipmanna101 check it now, all issue has been resolved

**Comment by ayush-848** [comment]
@arghadipmanna101  check it now, all issue has been resolved

**Comment by ayush-848** [comment]
@arghadipmanna101 please check it before another conflict arises

**Comment by ayush-848** [comment]
@arghadipmanna101 please check its been days since I have fixed it

**Comment by ayush-848** [comment]
@arghadipmanna101 Please check it

**Pull request closed without merging**
