### PR TITLE
Added the feature to auto comment on a new issue creation

### LINKED ISSUE #714: Feature for auto commenting on a new issue creation
I would like an automated feature that posts a predefined comment on an issue as soon as it is created. This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

Could you please assign me this issue under GSSOC'24.

### PR DESCRIPTION
**Pull request by suhanipaliwal**
## Related Issue
Fixes #714 

## Description
I have added auto-comment-on-issue.yml in .github/workflows directory. This file will add the feature of auto commenting when a new issue is created.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
There have some  issue check it once .

**Comment by suhanipaliwal** [comment]
I have checked it and I don't think there are any issues. Can you please specify what issue you faced?

**Comment by arghadipmanna101** [comment]
Do Git pull and then commit all your code and push them. Then recreate new PR.

**Comment by suhanipaliwal** [comment]
> Do Git pull and then commit all your code and push them. Then recreate new PR.

This issue simply involves adding a file in the .github directory to add the necessary workflow. Git pull is not necessary for this issue. Could you please merge this pr and add the labels for gssoc.

**Pull request closed without merging**
