### PR TITLE
feedback

### PR DESCRIPTION
**Pull request by solanki505**
## Related Issue
#1033 
## Description
double clicking the icon feedback page will pop out, I have added a modal feedback form which will take star rating as well and save the feedback form and submit it successfully.
## Type of PR

- [x] Feature enhancement

## Screenshots / videos (if applicable)

https://github.com/arghadipmanna101/Flipkart_Clone/assets/158484284/a245f862-e2d6-41ac-a082-12c607245040

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by solanki505** [comment]
@arghadipmanna101 sir please preview this pull request

**Comment by solanki505** [comment]
@arghadipmanna101  Please review the PR and merge this pull request.

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once. 

This is not perfect place to add this , plz replace it : 
image

**Comment by solanki505** [comment]
okay I am making the changes

**Pull request closed without merging**
