### PR TITLE
Adding CSS to button

### PR DESCRIPTION
**Pull request by Garima-149**
Screenshot (50)
@arghadipmanna101 I have added some CSS to button.Please check . This pull request had some merging conflicts before hence,I made another PR.

### CODE REVIEW

**Comment by Garima-149** [comment]
@arghadipmanna101  Now please check .All issues are resolved.

**Comment by arghadipmanna101** [comment]
work on the updated page.

**Comment by arghadipmanna101** [comment]
> work on the updated page.

Run git pull command and then recommit all update. ok

**Comment by Garima-149** [comment]
work on the updated page.
@arghadipmanna101 
Do I have to make some more changes to button?

**Comment by Garima-149** [comment]
@arghadipmanna101 please reply?

**Comment by Garima-149** [comment]
Please reply of text I messaged you

**Pull request closed without merging**
