### PR TITLE
nav bar correcting done

### PR DESCRIPTION
**Pull request by AryanAwtar**
## Related Issue
#1231
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Screenshot 2024-06-16 124315
edited
Screenshot 2024-06-16 124325
original

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by AryanAwtar** [comment]
Please add the tag of gssoc

**Comment by arghadipmanna101** [comment]
There have some conflict issue

**Comment by arghadipmanna101** [comment]
There have some conflict issue, check it once and the recreate a new PR

**Comment by AryanAwtar** [comment]
sorry 
can you please tell what is the conflict issue and how to resolve it
it is some thing with Greetings/welcome

**Pull request closed without merging**
