### PR TITLE
Carousel

### PR DESCRIPTION
**Pull request by maradadivyasree020**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
Carousel Modified.
## Description
[Please include a brief description of the changes or features added]
Used Flowbite to modify the carousel.
## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Before
Screenshot 2024-06-15 220111 bf
After
Screenshot 2024-06-15 222507 af1

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by maradadivyasree020** [comment]
Once please check Greetings / welcome (pull_request_target)  is failing

**Comment by maradadivyasree020** [comment]
Please review

**Comment by arghadipmanna101** [comment]
There have some conflict issue

**Comment by maradadivyasree020** [comment]
should i send a pr again?

**Comment by maradadivyasree020** [comment]
please review how can i remove the conflict

**Comment by maradadivyasree020** [comment]
please review

**Comment by arghadipmanna101** [comment]
There have some conflict issue

**Comment by maradadivyasree020** [comment]
i have resolved the conflicts please review

**Comment by maradadivyasree020** [comment]
please merge it and assign labels

**Comment by maradadivyasree020** [comment]
please merge it and assign labels

**Pull request merged**
