### PR TITLE
"Best for you" section styling

### PR DESCRIPTION
**Pull request by Archiesachin**
## Related Issue
#937 

## Description

Screenshot (1074)

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

Please merge this PR. Also add gssoc and level labels in the related issue and the PR.

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
There have some conflict issue check it once.

**Comment by Archiesachin** [comment]
> There have some conflict issue check it once.

Resolved the merge conflicts

**Comment by arghadipmanna101** [comment]
still have.

**Comment by Archiesachin** [comment]
Screenshot (1083)



Resolved

**Comment by Archiesachin** [comment]
> > Screenshot (1083)
> > Resolved
> 
> So, why this is showing? image




I'll create a new PR with the same issue by forking the repo again. Maybe the conflicts will not occur then.

**Pull request closed without merging**
