### PR TITLE
UI/UX of Footer #805

### PR DESCRIPTION
**Pull request by GauriGA**
**Description**
This pull request includes redesigning the footer section to improve its layout, aesthetics, and responsiveness. The new footer is organised into three main sections: About, Help, and Social/Contact. Additionally, some margin has been added to ensure it doesn't touch the section above.

**Type of PR**
 Feature enhancement

**Screenshots/videos (if applicable)** 
image

**Checklist:**
 I have performed a self-review of my code.
 I have read and followed the Contribution Guidelines.
 I have tested the changes thoroughly before submitting this pull request.
 I have provided relevant issue numbers, screenshots, and videos after making the changes.
 I have commented on my code, particularly in hard-to-understand areas.

**Additional context:**
The redesigned footer ensures a better user experience with a modern layout and improved responsiveness. The sections are clearly defined, making navigation easier for users. The margin adjustment prevents the footer from overlapping with the content above.

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
image

what is this man? check it once

**Comment by GauriGA** [comment]
@arghadipmanna101 I don't know, I think there is some glitch because it is working perfectly on my side.
image
image
image
image
image
image
image

**Comment by arghadipmanna101** [comment]
ok. close the pr . and git pull on your local device and make a new pr ok

**Comment by GauriGA** [comment]
@arghadipmanna101 Should I just close this PR? Did you merge it with the main branch?
And for the next issue i.e. of the cards, I should open a new pull request?

**Pull request closed without merging**
