### PR TITLE
index.html

### PR DESCRIPTION
**Pull request by Meetjain1**
Updated faviocn
flipkart favicon-modified

### CODE REVIEW

**Comment by Meetjain1** [comment]
@arghadipmanna101 any issues with this pr sir , Let me know ?

**Comment by Meetjain1** [comment]
@arghadipmanna101 any issue with this PR sir let me know

**Comment by Meetjain1** [comment]
@arghadipmanna101 sir , any issue in this PR let me know . Thankyou

**Comment by Meetjain1** [comment]
@arghadipmanna101 This Pr is related to issue #129

**Comment by Meetjain1** [comment]
@arghadipmanna101 please merge this sir

**Comment by arghadipmanna101** [comment]
already solved

**Comment by Meetjain1** [comment]
@arghadipmanna101 okk sir

**Pull request closed without merging**
