### PR TITLE
Added Search Button and Countdown Timer for Offers.html page

### PR DESCRIPTION
**Pull request by coderiksenthil**
## Related Issue
#1357 

## Description
The offer.html page should include a search button to help users quickly find specific offers and a countdown timer to indicate how long each offer will remain available. The search functionality will allow users to filter offers based on keywords, while the countdown timer will display the remaining time for each offer to create a sense of urgency.

For the search button, I’d like a search function that filters offers in real-time based on user input, updating the page with matching results. For the countdown timer, I’d like it to dynamically count down days, hours, minutes, and seconds until each offer expires, ensuring users are aware of how much time is left to take advantage of the deals.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Before (without a search bar and countdown)
image
After (with a search bar and countdown)
image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]
As alternatives, implementing a dropdown filter or sorting options would not effectively provide the same real-time search experience as the search button. Regarding the countdown timer, static expiration dates or manually updated statuses do not offer real-time updates, which are crucial for maintaining user engagement and urgency.

### CODE REVIEW

**Comment by coderiksenthil** [comment]
@arghadipmanna101 Can you merge my PR, it has been a week

**Comment by arghadipmanna101** [comment]
work on updated website

**Comment by coderiksenthil** [comment]
sure

**Comment by coderiksenthil** [comment]
There are no conflict, Please merge my PR when free

**Pull request merged**
