### PR TITLE
Added flipkart icon and title name same as that of flipkart website

### PR DESCRIPTION
**Pull request by SadafKausar2025**
when we are cloning any  website it is very important to give favicon and title name same as origenal website .

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
please assigned this issue to me #28
I will fixed it

**Comment by arghadipmanna101** [comment]
@SadafKausar2025 thanks for your contribution.

**Comment by SadafKausar2025** [comment]
hi @arghadipmanna101 

can you please give gssoc label in this PR?

**Comment by SadafKausar2025** [comment]
hello @arghadipmanna101 
this PR is not showing in my contribution.
I think you should also assign me then only level point will be added

**Comment by arghadipmanna101** [comment]
> hello @arghadipmanna101 this PR is not showing in my contribution. I think you should also assign me then only level point will be added

done

**Comment by SadafKausar2025** [comment]
Thank you

**Pull request merged**
