### PR TITLE
three dot width is changed

### PR DESCRIPTION
**Pull request by shivathmikavemula**
Hello PA
I have made a change in the width of the three dots.

### Screenshot -
Screenshot (12)

### CODE REVIEW

**Comment by shivathmikavemula** [comment]
I have completed my task please look at this and also please provide the gssoc levels @arghadipmanna101

**Comment by shivathmikavemula** [comment]
bright and dark modes are hiding the cart items #712
### Issue no #712 
@arghadipmanna101 
Please assign the gssoc labels to it.

**Comment by shivathmikavemula** [comment]
DOC: Update Contribution Guide with git pull upstream #706 @arghadipmanna101 
### Issue number #706 
I request you to provide the gssoc level to it.
@arghadipmanna101

**Comment by arghadipmanna101** [comment]
There have some issues check it once

**Pull request closed without merging**
