### PR TITLE
added Login pop up

### LINKED ISSUE #1263: Feat: login pop up on opening
### Describe the feature

When the website opens we should get a login popup

### Describe the solution you'd like

i want to add a login pop up

### Describe alternatives you've considered

no

### Add ScreenShots

image
Like this we should get

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
## Related Issue
Added Login pop As original flipkart

## Description
closes #1263 
Added Login pop As original flipkart
## Type of PR

- [ ] Bug fix
- [x ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x ] I have performed a self-review of my code
- [x ] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
@arghadipmanna101  can you please review the pull request soon so that i can work on another pull requests

**Comment by Saipradyumnagoud** [comment]
@arghadipmanna101  please review it soon

**Comment by Saipradyumnagoud** [comment]
image
This is the reason for those lines ,its display is not blocked that should be hidden

**Comment by Saipradyumnagoud** [comment]
image

now you can see there are no buttons.

**Comment by Saipradyumnagoud** [comment]
@arghadipmanna101 Please Review the pull Request i have updated the requested changes

**Comment by arghadipmanna101** [comment]
conflicts issue

**Comment by Saipradyumnagoud** [comment]
Now No conflicts @arghadipmanna101

**Comment by arghadipmanna101** [comment]
Error : 
-------

Before try to enter mobile no. 
image

After try to enter mobile no.
image

**Comment by Saipradyumnagoud** [comment]
@arghadipmanna101 There are few conflicts in the files so let me discard and work again

**Pull request closed without merging**
