### PR TITLE
readme info added

### PR DESCRIPTION
**Pull request by shivathmikavemula**
Hello PA,
I have added the readme information in readme.md file

### Screenshot -
Screenshot (10)

### CODE REVIEW

**Comment by shivathmikavemula** [comment]
I have made a change in the README.d file so please check it and allot the respective gssoc level 
@arghadipmanna101

**Comment by shivathmikavemula** [comment]
Are their any changes to be done in the readme.md file
@arghadipmanna101

**Comment by shivathmikavemula** [comment]
DOC: Update Contribution Guide with git pull upstream https://github.com/arghadipmanna101/Flipkart_Clone/issues/706 @arghadipmanna101

### Issue number #706
I request you to provide the gssoc level to it.
@arghadipmanna101

**Comment by arghadipmanna101** [comment]
There have some issues check it once

**Comment by shivathmikavemula** [comment]
I think their is only one issue in the 6th point @arghadipmanna101 
#706

**Comment by arghadipmanna101** [comment]
There have some issue . check it once

**Pull request merged**
