### PR TITLE
Fixed all Navbar issue

### LINKED ISSUE #242: hover effect on navbar items
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is no proper hovering effect in the nav bar . It needs an improvement ...

kindly assign me this issue as I already created the nav bar for website like amazon.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Ansh101112**
## Description
This pull request addresses issue #242 by adding and fetching the navbar content successfully, linking the pages, and fixing the UI error.

## Changes Made
- Added navbar content successfully.
- Linked the pages.
- Fixed UI error.

## Screenshots:
Screenshot (68)

## Checklist
- [x] Added navbar content
- [x] Linked the pages
- [x] Fixed UI error

## Related Issues
Closes #242 #237 #228 #202 #153 #128 #125 #37 #20 #106 

@arghadipmanna101 please close these issues as they are same issues and this single pr covers all these issues solution.

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
This is not working properly

**Comment by Ansh101112** [comment]
it is sir please share the issues clearly

**Comment by Ansh101112** [comment]
@arghadipmanna101 sir please close those isssues that i have tagged in my pr as it will make easy for fellow contributors and thanks for merging.

**Comment by arghadipmanna101** [comment]
> @arghadipmanna101 sir please close those isssues that i have tagged in my pr as it will make easy for fellow contributors and thanks for merging.

close it by yourself. thanks for contribute

**Comment by Ansh101112** [comment]
@arghadipmanna101 sir i dont have access to close the issues only owner of that issue have.

**Comment by Ansh101112** [comment]
@arghadipmanna101 sir please add gssoc and level badge asap

**Comment by Ansh101112** [comment]
@arghadipmanna101 please assign me on this merged pr.

**Pull request merged**
