### PR TITLE
Navbar footer

### PR DESCRIPTION
**Pull request by Varsani2520**
i remove the your not working part and not well-structured code 
that's why i redesigned the flipkart_home page look like is:
image
and the footer is :
image

### CODE REVIEW

**Comment by Varsani2520** [comment]
if you want  to show the output Follow the steps:
1.right click on the index.html file 
2. select open in default browser

**Comment by arghadipmanna101** [comment]
once do git pull operation then do git push. because your pr is not updated. ok

**Comment by Varsani2520** [comment]
check the PR and merged it @arghadipmanna101

**Comment by Varsani2520** [comment]
@arghadipmanna101 
i completed as you say check it #201  and merge it 
image

**Comment by Varsani2520** [comment]
Hi @arghadipmanna101 ,
why you can not merged it ?
its your responsibility to check this and merged it 
i completely create like a flipkart home page ..
give me a response.

**Comment by Varsani2520** [comment]
Hey @arghadipmanna101 ,
give me response within a hour 

otherwise i complaint in gssoc

**Comment by sanjay-kv** [comment]
@Varsani2520 I will look into this, let me reach out to the admin

**Comment by sanjay-kv** [comment]
@arghadipmanna101 

as a admin you can either close the PR, or let contributor know whats happening also you have not yet invited me to the repo, not sure whats really happening in this repo.

**Pull request closed without merging**
