### PR TITLE
Login and Sign Up page

### LINKED ISSUE #1421: Feature Request : Make login page more impressive
### Describe the feature

I want Make login page more impressive, by making it look good

## I need to make Login page look more attractive like :
WhatsApp Image 2024-07-19 at 23 48 33_e4f5409f

### Describe alternatives you've considered

NA

## Before:

image

## I need to make Login page look more attractive like :
WhatsApp Image 2024-07-19 at 23 48 33_e4f5409f

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by sreevidya-16**
## Related Issue
Fixes #1421 issue

## Description
I added Login and Sign up page more impressive and creative, with high authentication

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

https://github.com/user-attachments/assets/b5609bdc-3c55-49d3-bfe4-347f6053483f

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by sreevidya-16** [comment]
@arghadipmanna101, view this PR
If any changes are required please let me know
Otherwise, kindly merge into main sir

**Comment by csathnere** [comment]
fully copy [youtube link ](https://youtu.be/T9GsdKIXaVs?feature=shared)
Add Flipkart name and logo.

**Comment by sreevidya-16** [comment]
Screenshot (786)
Screenshot (787)


I have updated PR @arghadipmanna101, kindly view this and if you require any changes, please let me know

**Comment by sreevidya-16** [comment]
@csathnere, view updated PR

**Pull request merged**
