### PR TITLE
Update 404.html

### PR DESCRIPTION
**Pull request by csathnere**
## Issue
image not show 

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Screenshot (13)

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
There have some conflict issue

**Comment by csathnere** [comment]
All conflicts have been cleared

**Comment by arghadipmanna101** [comment]
Issue : 
image
No drop-down effect.

**Comment by csathnere** [comment]
no response....

**Pull request closed without merging**
